### ISSUE TITLE
Can't move the actor in demo.

### ISSUE THREAD

**Issue by Colmar-zlicheng** [RosettaWYzhang/Roam#2]
Hi, I try to run the RoamDemo in Unity, but I can't control the actor, and the actor is always stick in the ground.

![截屏2024-06-13 11 53 28](https://github.com/RosettaWYzhang/Roam/assets/111580763/353f8ffb-b301-431d-be9d-5e5c94569f93)

**Comment by RosettaWYzhang** [comment]
Hi! My guess is that Neural Network is not set. In order to control the character, can you please check if the UI options are the same as the one below?
![ui_unity](https://github.com/RosettaWYzhang/Roam/assets/23449013/28f0d177-5b97-442c-a1cc-4855d4c76106)

**Comment by Colmar-zlicheng** [comment]
Thank you for your reply, I have checked the UI options as below. I still can't control the actor.

![截屏2024-06-13 17 51 18](https://github.com/RosettaWYzhang/Roam/assets/111580763/de52e235-4d32-4772-a25c-196eeb2dec31)

**Comment by RosettaWYzhang** [comment]
This is strange. Can you please check the following:
- Is the L_NSM script above Roam_Demo enabled?
- Do you see any error message when you hit/disable the play button? or any compilation error when you first open the demo? 
- Does the character always stick to the ground when you enable and disable the High Level option?
- Can you give more details about the unity version and system specs? (I only tested on Windows 10, Unity version 2021.3.14)

**Comment by Colmar-zlicheng** [comment]
Hi, thank you for your reply

1. Yes
2. I get `Prefab instance problem: cf88ae03d8cc2fabfcce6278f5ffb13a_pose1678_coord_scale_mesh_world (Missing Prefab with guid: 7c8669313b1c8704781fb2db823787c1)` when first open the demo.
3. Yes
4. I use Mac and Unity 2021.3.14

**Comment by RosettaWYzhang** [comment]
Thanks for notifying me this problem! I pushed a fix and tested it on mac. It should work now.
Can you please try again?

**Comment by Colmar-zlicheng** [comment]
It can works now, thank you!
